version: '3'

services:

  app:
    build: .
    container_name: rate-limiter-app
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    container_name: rate-limiter-redis
    expose:
      - 6379
    ports:
      - "6379:6379"