version: '3'

services:

  redis:
    image: redis:alpine
    container_name: rate-limiter-redis
    expose:
      - 6379

  mysql:
    image: mysql:8.0.30-debian
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rate_limiter
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: rate-limiter-app
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always