version: '3'

services:

  app:
    build: .
    container_name: rate-limiter-app
    volumes:
      - .:/go/src
    ports:
      - "8080:8080"

  redis:
    image: redis:alpine
    container_name: rate-limiter-redis
    expose:
      - 6379

  mysql:
    image: mysql:8.0.30-debian
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rate_limiter